# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 07:16
from __future__ import unicode_literals

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('test', app01.models.MyCharField(max_length=32)),
            ],
        ),
    ]
