# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
