# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180621_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', related_query_name='book123', to='app01.Author'),
        ),
    ]
